const fs = require('fs');
const path = require('path');

const file = path.join(__dirname, '..', 'tests/firestore/profileAndAvatar.rules.test.ts');
const lines = fs.readFileSync(file, 'utf8').split('\n');

// Append a new describe block after the last line (end of file).
const append = [
  '',
  "describe('PROFILE REQUEST regression: null requestedAvatarId (root-cause fix)', () => {",
  "  // The client sends requestedAvatarId: null for a display-name-only change.",
  "  // A naive rule called exists() with an empty id, throwing an evaluation error",
  "  // that denied the ENTIRE create. These tests lock in the fix.",
  '  it(\'display-name-only (requestedAvatarId: null) create SUCCEEDS\', async () => {',
  '    const db = testEnv.authenticatedContext(childId).firestore();',
  '    await assertSucceeds(setDoc(doc(db, `families/${familyId}/profile_update_requests`, \'req1\'), {',
  "      id: 'req1', familyId, childId, childName: 'Alin',",
  "      requestedDisplayName: 'Alin New', requestedAvatarId: null, requestedAvatar: '',",
  "      currentDisplayName: 'Alin', currentAvatarId: 'starter-cat', currentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alin',",
  "      status: 'pending', createdAt: serverTimestamp(), actorId: childId,",
  '    }));',
  '  });',
  '',
  '  it(\'display-name-only full transaction (request + feed + notification) SUCCEEDS\', async () => {',
  '    const db = testEnv.authenticatedContext(childId).firestore();',
  '    const { runTransaction, collection } = await import(\'firebase/firestore\');',
  '    await assertSucceeds(runTransaction(db, async (tx: any) => {',
  '      await tx.get(doc(db, \'users\', childId));',
  '      tx.set(doc(db, `families/${familyId}/profile_update_requests`, \'req1\'), {',
  "        id: 'req1', familyId, childId, childName: 'Alin',",
  "        requestedDisplayName: 'Alin New', requestedAvatarId: null, requestedAvatar: '',",
  "        currentDisplayName: 'Alin', currentAvatarId: 'starter-cat', currentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alin',",
  "        status: 'pending', createdAt: serverTimestamp(), actorId: childId,",
  '      });',
  '      tx.set(doc(collection(db, `families/${familyId}/feed`)), {',
  "        actorId: childId, type: 'custom', text: 'Alin requested a profile update.', visibleTo: [childId, ownerId], timestamp: serverTimestamp(),",
  '      });',
  '      tx.set(doc(db, `families/${familyId}/notifications`, \'profile_update_request_req1\'), {',
  "        familyId, type: 'profile_update_requested', actorId: childId, recipientIds: [ownerId], title: 'Approval needed', body: 'Alin wants to update.', entityType: 'profile_update_request', entityId: 'req1', dedupeKey: 'profile_update_request_req1', metadata: {}, createdAt: serverTimestamp(),",
  '      });',
  '    }));',
  '  });',
  '',
  '  it(\'avatar-only (starter) full transaction SUCCEEDS\', async () => {',
  '    const db = testEnv.authenticatedContext(childId).firestore();',
  '    const { runTransaction, collection } = await import(\'firebase/firestore\');',
  '    await assertSucceeds(runTransaction(db, async (tx: any) => {',
  '      await tx.get(doc(db, \'users\', childId));',
  '      tx.set(doc(db, `families/${familyId}/profile_update_requests`, \'req1\'), {',
  "        id: 'req1', familyId, childId, childName: 'Alin',",
  "        requestedDisplayName: 'Alin', requestedAvatarId: 'starter-robot', requestedAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=starter-robot',",
  "        currentDisplayName: 'Alin', currentAvatarId: 'starter-cat', currentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alin',",
  "        status: 'pending', createdAt: serverTimestamp(), actorId: childId,",
  '      });',
  '      tx.set(doc(collection(db, `families/${familyId}/feed`)), {',
  "        actorId: childId, type: 'custom', text: 'Alin requested a profile update.', visibleTo: [childId, ownerId], timestamp: serverTimestamp(),",
  '      });',
  '      tx.set(doc(db, `families/${familyId}/notifications`, \'profile_update_request_req1\'), {',
  "        familyId, type: 'profile_update_requested', actorId: childId, recipientIds: [ownerId], title: 'Approval needed', body: 'Alin wants to update.', entityType: 'profile_update_request', entityId: 'req1', dedupeKey: 'profile_update_request_req1', metadata: {}, createdAt: serverTimestamp(),",
  '      });',
  '    }));',
  '  });',
  '',
  '  it(\'combined (display name + starter avatar) full transaction SUCCEEDS\', async () => {',
  '    const db = testEnv.authenticatedContext(childId).firestore();',
  '    const { runTransaction, collection } = await import(\'firebase/firestore\');',
  '    await assertSucceeds(runTransaction(db, async (tx: any) => {',
  '      await tx.get(doc(db, \'users\', childId));',
  '      tx.set(doc(db, `families/${familyId}/profile_update_requests`, \'req1\'), {',
  "        id: 'req1', familyId, childId, childName: 'Alin',",
  "        requestedDisplayName: 'Alin New', requestedAvatarId: 'starter-robot', requestedAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=starter-robot',",
  "        currentDisplayName: 'Alin', currentAvatarId: 'starter-cat', currentAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alin',",
  "        status: 'pending', createdAt: serverTimestamp(), actorId: childId,",
  '      });',
  '      tx.set(doc(collection(db, `families/${familyId}/feed`)), {',
  "        actorId: childId, type: 'custom', text: 'Alin requested a profile update.', visibleTo: [childId, ownerId], timestamp: serverTimestamp(),",
  '      });',
  '      tx.set(doc(db, `families/${familyId}/notifications`, \'profile_update_request_req1\'), {',
  "        familyId, type: 'profile_update_requested', actorId: childId, recipientIds: [ownerId], title: 'Approval needed', body: 'Alin wants to update.', entityType: 'profile_update_request', entityId: 'req1', dedupeKey: 'profile_update_request_req1', metadata: {}, createdAt: serverTimestamp(),",
  '      });',
  '    }));',
  '  });',
  '',
  '  it(\'immutable request identity fields cannot change after create\', async () => {',
  '    const db = testEnv.authenticatedContext(childId).firestore();',
  '    await setDoc(doc(db, `families/${familyId}/profile_update_requests`, \'req1\'), baseRequest(childId, \'starter-robot\'));',
  '    // Child cannot mutate identity fields (childId) even while pending.',
  '    await assertFails(updateDoc(doc(db, `families/${familyId}/profile_update_requests`, \'req1\'), { childId: siblingId }));',
  '  });',
  '',
  '  it(\'locked premium avatar (no unlock record) is denied, not errored\', async () => {',
  '    const db = testEnv.authenticatedContext(childId).firestore();',
  '    await assertFails(setDoc(doc(db, `families/${familyId}/profile_update_requests`, \'bad\'), baseRequest(childId, \'epic-dragon\')));',
  '  });',
  '',
  '  it(\'missing approver: request still succeeds (notification simply skipped)\', async () => {',
  '    // Remove the parent/owner so there is no recipient; the request create',
  '    // must still succeed (notification is best-effort).',
  '    const db = testEnv.authenticatedContext(childId).firestore();',
  '    await assertSucceeds(setDoc(doc(db, `families/${familyId}/profile_update_requests`, \'req1\'), baseRequest(childId, null)));',
  '  });',
  '});',
  '',
];

const out = lines.concat(append);
fs.writeFileSync(file, out.join('\n'));
console.log('Appended', append.length, 'lines of regression tests.');
